### ISSUE TITLE
[Bug]  Disabled Groups/Combos show up in Picker window

### ISSUE THREAD

**Issue by 360path** [xmichelo/Beeftext#469]
#### Expected behavior

Disabled Groups and Combos are not shown in the Picker window.

#### Actual behavior

Disabled Groups and Combos are still shown in the Picker window.

#### Steps to reproduce the behavior

- Disable a Group or Combo.
- Call the Picker window.
- Disabled Groups and Combos are still shown.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v13.0

#### Operating system version (e.g Windows 10)

Windows 10

**Comment by xmichelo** [comment]
Hi.

May I ask you to double check. I addressed this some time ago and I just verified: If a combo is disabled (individually or because its group is disabled), it does not show up in the picker window. Also, could you check that you do not have duplicates of the combos that are located in other group. Finally, Please have a look at the `Help➜About Beeftext` dialog to verify you are running v13.0.

**Comment by 360path** [comment]
I can confirm I'm running v13.0.

Also, I checked again. If a combo is disabled, it will still show up in the picker window unless I start entering letters. Then only the enabled ones show up in the search.
I can make a screencast if necessary.

**Comment by xmichelo** [comment]
Hello. Thanks. No need for a screencast. The problem is clear. I'll investigate.
